name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    # Allows manual triggers of the workflow.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      # Step 4: Install dependencies
      - name: Install dependencies
        run: nix develop -c pnpm install

      # Step 5: Run scripts sequentially
      - name: "Run script 1: Clone JSCL"
        run: nix develop -c pnpm run 1:jscl_clone

      - name: "Run script 2: Build JSCL"
        run: nix develop -c pnpm run 2:jscl_build

      - name: "Run script 3: Archive JSCL"
        run: nix develop -c pnpm run 3:jscl_archive

      - name: "Run script 4: Build source"
        run: nix develop -c pnpm run 4:src_build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
