name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    # Allows manual triggers of the workflow.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Step 3: Set up SBCL
      - name: Install SBCL
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Run scripts sequentially
      - name: "Run script 1: Clone JSCL"
        run: pnpm run 1:jscl_clone

      - name: "Run script 2: Build JSCL"
        run: pnpm run 2:jscl_build

      - name: "Run script 3: Archive JSCL"
        run: pnpm run 3:jscl_archive

      - name: "Run script 4: Build source"
        run: pnpm run 4:src_build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment